# Generated by Django 4.0.2 on 2022-04-05 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='qr',
        ),
    ]
