# Generated by Django 4.0.2 on 2022-04-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0002_remove_object_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='object',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='object',
            name='summ',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='object',
            name='inv',
            field=models.CharField(max_length=1000),
        ),
    ]
