# Generated by Django 4.0.2 on 2022-04-05 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0003_object_code_object_count_object_summ_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='object',
            table='blackjack_object',
        ),
    ]
