# Generated by Django 4.0.2 on 2022-04-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0004_alter_object_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='qr',
            field=models.CharField(default='<qrcode.image.pil.PilImage object at 0x7fd05f5799a0>', max_length=1000000),
        ),
        migrations.AlterModelTable(
            name='object',
            table=None,
        ),
    ]
