# Generated by Django 4.0.2 on 2022-04-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0005_object_qr_alter_object_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='object',
            name='qr',
        ),
    ]
