# Generated by Django 4.0.2 on 2022-04-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackjack', '0006_remove_object_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='code',
            field=models.IntegerField(default=1, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='object',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='object',
            name='inv',
            field=models.CharField(max_length=1000, verbose_name='Инвентарный номер'),
        ),
        migrations.AlterField(
            model_name='object',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='object',
            name='note',
            field=models.TextField(verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='number',
            field=models.IntegerField(verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='object',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='object',
            name='summ',
            field=models.FloatField(verbose_name='Сумма'),
        ),
    ]
